Update patch set 2
Patch Set 2: Code-Review-1

adminstrator@adminstrator-Satellite-M300:~/android/system$ scp -p -P 29418 iKillCypher2@review.cyanogenmod.org:hooks/commit-msg kernel/sony/apq8064/.git/hooks
commit-msg                                                                                           100% 4361     4.3KB/s   00:00    
adminstrator@adminstrator-Satellite-M300:~/android/system$ curl -Lo kernel/sony/apq8064/.git/hooks/commit-msg iKillCypher2@review.cyanogenmod.org:hooks/commit-msg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0      2      0  0:00:04  0:00:03  0:00:01     2
adminstrator@adminstrator-Satellite-M300:~/android/system$ chmod u+x kernel/sony/apq8064/.git/hooks/commit-msg
adminstrator@adminstrator-Satellite-M300:~/android/system$ cd android/system/kernel/sony/apq8064/arch/arm/lib
bash: cd: android/system/kernel/sony/apq8064/arch/arm/lib: No such file or directory
adminstrator@adminstrator-Satellite-M300:~/android/system$ cd ~/android/system/kernel/sony/apq8064/arch/arm/lib
adminstrator@adminstrator-Satellite-M300:~/android/system/kernel/sony/apq8064/arch/arm/lib$ repo upload
Counting objects: 6, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 2.15 KiB | 0 bytes/s, done.
Total 6 (delta 5), reused 0 (delta 0)
remote: Resolving deltas: 100% (5/5)
remote: Processing changes: refs: 1, done    
remote: ERROR: missing Change-Id in commit message footer
remote: Suggestion for commit message:
remote: ARM: 7668/1: fix memset-related crashes caused by recent GCC (4.7.2) optimizations
remote: 
remote: Recent GCC versions (e.g. GCC-4.7.2) perform optimizations based on
remote: assumptions about the implementation of memset and similar functions.
remote: The current ARM optimized memset code does not return the value of
remote: its first argument, as is usually expected from standard implementations.
remote: 
remote: For instance in the following function:
remote: 
remote: void debug_mutex_lock_common(struct mutex *lock, struct mutex_waiter *waiter)
remote: {
remote: 	memset(waiter, MUTEX_DEBUG_INIT, sizeof(*waiter));
remote: 	waiter->magic = waiter;
remote: 	INIT_LIST_HEAD(&waiter->list);
remote: }
remote: 
remote: compiled as:
remote: 
remote: 800554d0 <debug_mutex_lock_common>:
remote: 800554d0:       e92d4008        push    {r3, lr}
remote: 800554d4:       e1a00001        mov     r0, r1
remote: 800554d8:       e3a02010        mov     r2, #16 ; 0x10
remote: 800554dc:       e3a01011        mov     r1, #17 ; 0x11
remote: 800554e0:       eb04426e        bl      80165ea0 <memset>
remote: 800554e4:       e1a03000        mov     r3, r0
remote: 800554e8:       e583000c        str     r0, [r3, #12]
remote: 800554ec:       e5830000        str     r0, [r3]
remote: 800554f0:       e5830004        str     r0, [r3, #4]
remote: 800554f4:       e8bd8008        pop     {r3, pc}
remote: 
remote: GCC assumes memset returns the value of pointer 'waiter' in register r0; causing
remote: register/memory corruptions.
remote: 
remote: This patch fixes the return value of the assembly version of memset.
remote: It adds a 'mov' instruction and merges an additional load+store into
remote: existing load/store instructions.
remote: For ease of review, here is a breakdown of the patch into 4 simple steps:
remote: 
remote: Step 1
remote: ======
remote: Perform the following substitutions:
remote: ip -> r8, then
remote: r0 -> ip,
remote: and insert 'mov ip, r0' as the first statement of the function.
remote: At this point, we have a memset() implementation returning the proper result,
remote: but corrupting r8 on some paths (the ones that were using ip).
remote: 
remote: Step 2
remote: ======
remote: Make sure r8 is saved and restored when (! CALGN(1)+0) == 1:
remote: 
remote: save r8:
remote: -       str     lr, [sp, #-4]!
remote: +       stmfd   sp!, {r8, lr}
remote: 
remote: and restore r8 on both exit paths:
remote: -       ldmeqfd sp!, {pc}               @ Now <64 bytes to go.
remote: +       ldmeqfd sp!, {r8, pc}           @ Now <64 bytes to go.
remote: (...)
remote:         tst     r2, #16
remote:         stmneia ip!, {r1, r3, r8, lr}
remote: -       ldr     lr, [sp], #4
remote: +       ldmfd   sp!, {r8, lr}
remote: 
remote: Step 3
remote: ======
remote: Make sure r8 is saved and restored when (! CALGN(1)+0) == 0:
remote: 
remote: save r8:
remote: -       stmfd   sp!, {r4-r7, lr}
remote: +       stmfd   sp!, {r4-r8, lr}
remote: 
remote: and restore r8 on both exit paths:
remote:         bgt     3b
remote: -       ldmeqfd sp!, {r4-r7, pc}
remote: +       ldmeqfd sp!, {r4-r8, pc}
remote: (...)
remote:         tst     r2, #16
remote:         stmneia ip!, {r4-r7}
remote: -       ldmfd   sp!, {r4-r7, lr}
remote: +       ldmfd   sp!, {r4-r8, lr}
remote: 
remote: Step 4
remote: ======
remote: Rewrite register list "r4-r7, r8" as "r4-r8".
remote: 
remote: Signed-off-by: Ivan Djelic <ivan.djelic@parrot.com>
remote: Reviewed-by: Nicolas Pitre <nico@linaro.org>
remote: Signed-off-by: Dirk Behme <dirk.behme@gmail.com>
remote: Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>
remote: 
remote: Change-Id: I16bfdf2e4f2b992604c7b43d8e8ba162ae9f265a
remote: 
remote: Hint: To automatically insert Change-Id, install the hook:
remote:   gitdir=$(git rev-parse --git-dir); scp -p -P 29418 iKillCypher2@review.cyanogenmod.org:hooks/commit-msg ${gitdir}/hooks/
remote: 
remote: 
To ssh://iKillCypher2@review.cyanogenmod.org:29418/CyanogenMod/android_kernel_sony_apq8064
 ! [remote rejected] changess -> refs/for/cm-12.0 (missing Change-Id in commit message footer)
error: failed to push some refs to 'ssh://iKillCypher2@review.cyanogenmod.org:29418/CyanogenMod/android_kernel_sony_apq8064'

----------------------------------------------------------------------
[FAILED] kernel/sony/apq8064/ changess        (Upload failed)

adminstrator@adminstrator-Satellite-M300:~/android/system/kernel/sony/apq8064/arch/arm/lib$ 

any idea whats is going on ?

Patch-set: 2
Label: Code-Review=-1